// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppTN_h__
#define __RcppTN_h__

#include "RcppTN_RcppExports.h"

#endif // __RcppTN_h__
